# Generated by Django 5.2.7 on 2025-11-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Image Item', 'verbose_name_plural': 'Image Items'},
        ),
        migrations.AlterModelOptions(
            name='processedversion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Processed Version', 'verbose_name_plural': 'Processed Versions'},
        ),
    ]
